import { jsPDF } from "jspdf";

export async function generateAuditReport(company, overallScore, breakdown, checklists = [], risks = [], documents = [], managerName = "") {
  try {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4"
    });

    const primaryColor = [217, 119, 6]; // Solar amber
    const secondaryColor = [15, 23, 42]; // Slate-900
    const lightBg = [248, 250, 252]; // Slate-50

    const pageHeight = doc.internal.pageSize.height;
    const pageWidth = doc.internal.pageSize.width;

    const drawHeaderFooter = (pageNumber) => {
      // Top accent bar
      doc.setFillColor(...primaryColor);
      doc.rect(0, 0, pageWidth, 4, "F");

      // Footer text
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184); // slate-400
      doc.text("UK Solar SME Compliance Toolkit | Research Academic Showcase", 15, pageHeight - 10);
      doc.text(`Page ${pageNumber}`, pageWidth - 25, pageHeight - 10);
      doc.text("Thornton Science Park &bull; University of Chester", pageWidth / 2, pageHeight - 10, { align: "center" });
    };

    // ----------------------------------------------------
    // PAGE 1: COVER PAGE & SCORE CERTIFICATE
    // ----------------------------------------------------
    drawHeaderFooter(1);

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.setTextColor(...secondaryColor);
    doc.text("UK SOLAR SME COMPLIANCE", 15, 35);
    doc.text("AUDIT REPORT", 15, 45);

    // Subtitle
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(`Report Generated: ${new Date().toLocaleDateString("en-GB")} | System: Live Verification`, 15, 53);

    // Divider Line
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.line(15, 58, pageWidth - 15, 58);

    // Company Information Card
    doc.setFillColor(...lightBg);
    doc.roundedRect(15, 65, 180, 52, 3, 3, "F");
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(...secondaryColor);
    doc.text("COMPANY PROFILE DETAIL", 22, 74);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105); // slate-600
    
    doc.text(`Company Name: ${company?.companyName || "N/A"}`, 22, 82);
    doc.text(`Sector: Solar PV & Microgeneration Installer`, 22, 88);
    doc.text(`Head Office: ${company?.address || "Address details pending"}`, 22, 94);
    doc.text(`Contact Phone: ${company?.phone || "Phone details pending"}`, 22, 100);
    doc.text(`Lead Manager: ${managerName || "System Operator"}`, 22, 106);

    // Score Card Section
    doc.setFillColor(...secondaryColor);
    doc.roundedRect(15, 126, 180, 48, 3, 3, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(255, 255, 255);
    doc.text("OVERALL COMPLIANCE SCORE ASSESSMENT", 25, 137);

    // Draw score box
    doc.setFillColor(...primaryColor);
    doc.roundedRect(25, 145, 30, 20, 2, 2, "F");
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(255, 255, 255);
    doc.text(`${overallScore}%`, 40, 158, { align: "center" });

    // Performance label text
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    const scoreText = overallScore >= 80 ? "AUDIT PASS & COMPLIANT" : overallScore >= 50 ? "MITIGATION REQUIRED" : "CRITICAL DIRECTIVE ISSUED";
    doc.text(scoreText, 62, 151);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text("Weighted evaluation covers microgeneration accreditations, CDM safety filings,", 62, 157);
    doc.text("working at heights RAMS validation, and Distribution Network Operator grid notifications.", 62, 161);

    // Academic Supervisor Info Box
    doc.setDrawColor(245, 158, 11);
    doc.setFillColor(254, 243, 199); // yellow-100
    doc.roundedRect(15, 188, 180, 36, 2, 2, "FD");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(146, 64, 14); // amber-800
    doc.text("ACADEMIC STUDY DISCLAIMER", 22, 196);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(180, 83, 9); // amber-700
    doc.text("This document is generated by the UK Solar SME Compliance Toolkit, a system developed", 22, 203);
    doc.text("for postgraduate research in MSc Engineering Management at the University of Chester.", 22, 207);
    doc.text("All regulatory criteria are modelled from MCS schemes, Ofgem guidelines, and HSE standards.", 22, 211);
    doc.text("Businesses must independently verify electrical certifications (BS 7671) and DNO guidelines.", 22, 215);


    // ----------------------------------------------------
    // PAGE 2: CHECKLIST PROGRESS
    // ----------------------------------------------------
    doc.addPage();
    drawHeaderFooter(2);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...secondaryColor);
    doc.text("COMPLIANCE CHECKLIST PROGRESS", 15, 20);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(`Ticked tasks breakdown: ${breakdown.checklist.completed} completed of ${breakdown.checklist.total} total standard checks`, 15, 25);

    // Render Checklist Table
    let y = 32;
    doc.setDrawColor(226, 232, 240);
    doc.setFillColor(...lightBg);

    // Table Header
    doc.rect(15, y, 180, 8, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(...secondaryColor);
    doc.text("Task Specification", 18, y + 5.5);
    doc.text("Phase Grouping", 120, y + 5.5);
    doc.text("Audit Status", 170, y + 5.5);
    
    y += 8;

    checklists.forEach((task) => {
      if (y > pageHeight - 30) {
        doc.addPage();
        drawHeaderFooter(doc.internal.getNumberOfPages());
        y = 20;
      }

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(51, 65, 85);
      
      // Wrap task name text to fit
      const splitTaskName = doc.splitTextToSize(task.taskName, 95);
      const rowHeight = Math.max(8, splitTaskName.length * 5);

      // Draw bottom row line
      doc.line(15, y + rowHeight, 195, y + rowHeight);

      // Print wrapped text
      doc.text(splitTaskName, 18, y + 4.5);
      
      // Print phase name
      const simplePhase = task.phase.split(":")[0];
      doc.text(simplePhase, 120, y + 4.5);

      // Print status
      doc.setFont("helvetica", "bold");
      if (task.completed) {
        doc.setTextColor(22, 163, 74); // green-600
        doc.text("COMPLIANT", 170, y + 4.5);
      } else {
        doc.setTextColor(220, 38, 38); // red-600
        doc.text("PENDING", 170, y + 4.5);
      }

      y += rowHeight;
    });


    // ----------------------------------------------------
    // PAGE 3: RISK REGISTER & VERIFIED DOCUMENTS
    // ----------------------------------------------------
    doc.addPage();
    drawHeaderFooter(3);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...secondaryColor);
    doc.text("RISK REGISTER & MITIGATION SAFETY", 15, 20);

    // Risks Table
    y = 28;
    doc.setFillColor(...lightBg);
    doc.rect(15, y, 180, 8, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(...secondaryColor);
    doc.text("Risk Hazard", 18, y + 5.5);
    doc.text("Mitigation Action Plan", 75, y + 5.5);
    doc.text("Level", 155, y + 5.5);
    doc.text("Status", 175, y + 5.5);

    y += 8;

    risks.forEach((risk) => {
      if (y > 150) { // Limit risk area, start document checklist below
        return;
      }

      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(51, 65, 85);

      const splitRisk = doc.splitTextToSize(risk.potentialRisk, 52);
      const splitMitigation = doc.splitTextToSize(risk.mitigationAction, 76);
      
      const rowHeight = Math.max(12, splitMitigation.length * 4.5, splitRisk.length * 4.5);
      doc.line(15, y + rowHeight, 195, y + rowHeight);

      doc.text(splitRisk, 18, y + 4.5);
      doc.text(splitMitigation, 75, y + 4.5);
      
      // Level
      doc.setFont("helvetica", "bold");
      if (risk.riskLevel === "High") doc.setTextColor(220, 38, 38);
      else if (risk.riskLevel === "Medium") doc.setTextColor(217, 119, 6);
      else doc.setTextColor(37, 99, 235);
      doc.text(risk.riskLevel, 155, y + 4.5);

      // Status
      doc.setTextColor(71, 85, 105);
      doc.text(risk.status, 175, y + 4.5);

      y += rowHeight;
    });

    // Verified Document File Register
    y = Math.max(y + 12, 140);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(...secondaryColor);
    doc.text("VERIFIED CERTIFICATE DOCUMENT REGISTER", 15, y);
    y += 6;

    doc.setFillColor(...lightBg);
    doc.rect(15, y, 180, 8, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(...secondaryColor);
    doc.text("Document File Name", 18, y + 5.5);
    doc.text("Credential Classification", 100, y + 5.5);
    doc.text("Uploaded At Date", 160, y + 5.5);
    
    y += 8;

    documents.forEach((docu) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(51, 65, 85);

      doc.line(15, y + 8, 195, y + 8);
      doc.text(docu.documentName, 18, y + 5);
      
      const docTypePretty = docu.documentType === "insurance" 
        ? "Public Liability Insurance Policy"
        : docu.documentType === "mcs-certificate"
        ? "MCS Installer Accreditation Certificate"
        : docu.documentType === "electrical-certificate"
        ? "NICEIC / Competent Person Certificate"
        : docu.documentType === "risk-assessment"
        ? "RAMS Method Statement File"
        : "Commissioning Handover File";
      
      doc.text(docTypePretty, 100, y + 5);
      doc.text(new Date(docu.uploadedAt).toLocaleDateString("en-GB"), 160, y + 5);

      y += 8;
    });

    // Save PDF
    const fileName = `${company?.companyName?.replace(/\s+/g, "_") || "Solar_SME"}_Compliance_Audit_Report.pdf`;
    doc.save(fileName);
    return true;
  } catch (err) {
    console.error("PDF generation helper error:", err);
    return false;
  }
}
